### ISSUE TITLE
Linux port?

### ISSUE THREAD

**Issue by sphh** [cthing/meazure#12]
During my Windows time, I used this regularly as the best screen measurement tool!!!

Are there any plans to make it usable on Linux?

I tried to run it in `Wine`. It starts, the main window is shown, the magnifying glass works, but the crosshairs (and sometimes the area between them) are simple solid blocks...
![Untitled](https://user-images.githubusercontent.com/4856462/78463300-b2980500-76ca-11ea-8a20-4819a1290419.png)

**Comment by baron1405** [comment]
Thanks for the feedback. I do not have any immediate plans for a Linux port
due to being busy with my day job and other personal projects. I am
actually impressed that the old code base runs as well as it does on Wine.
Given the highly Window's specific code, it would be a rewrite to support a
different OS (e.g. Linux and Mac). I just need to find a way to clone
myself :-)

Regards,
Baron

**Comment by abrac** [comment]
@sphh 
I also use this tool on Linux. It looks a lot better for me if you can ignore the solid blocks (see [screenshot](https://user-images.githubusercontent.com/55248999/99144973-63a84a00-2673-11eb-9620-afada709f963.png)).

To fix your oversized fonts, I think that you might need to play around with your wine config. Open `winecfg` and play around with the dpi in the *graphics* tab.

**Comment by sphh** [comment]
I tried it again on a fresh install of Linux Mint 20, and now the font sizing is perfect without playing around with my wine config! The boxes are still there and sometimes the hairline becomes bold (I mean very bold: half the size of the boxes) and sometimes they don't follow the "blocks" around.

**Comment by abrac** [comment]
You described the issue perfectly. I can confirm that I also experience that. There's no workaround that I can think of though. If I get a bit of time, I'll ask on the Wine forums and will update this issue accordingly.

**Comment by xandro2021** [comment]
2 years later it's is finally usable out of the box using the application bottles selecting the default profile for applications (flatpak)
The only broken feature was the one to measure the widows applications (it only detected itselft and it's own panels which were the ones emulated by wine). But there are not those annoying color squares anymore and the other features looks fine. Although you have to struggle a bit to drag the pointers with the mouse (using the botons in the app to move works excellent though)
I'm using Fedora 36 spin (i3-wm).
I'm happy because I needed that app to start learning a CSS course in which the tutor is asking for picPick application which is another Only Windows application that does similar things (measure, color picker, and I don't know what more), but I guess I would be fine with measure and color pickers.
Maybe I should try running that other app in bottles too ;o, anyway, here are some pictures of my experience.
![2022-05-14-131253_2560x1440_scrot](https://user-images.githubusercontent.com/88587370/168446202-3353f7a7-3f84-4990-8ee9-f9b74894498b.png)
![2022-05-14-132502_2560x1440_scrot](https://user-images.githubusercontent.com/88587370/168446203-c2f251d8-060e-452e-8c2d-b9ceacb001f8.png)
![2022-05-14-132711_2560x1440_scrot](https://user-images.githubusercontent.com/88587370/168446204-18f82145-e293-45f0-8fa8-bee530c669fb.png)
![2022-05-14-133119_2560x1440_scrot](https://user-images.githubusercontent.com/88587370/168446205-90eeb6cf-88a0-4470-b0d8-488ef0eadad2.png)

**Comment by xandro2021** [comment]
Yeap, after trying the other app, I prefer this one. It's simple, very minimal but very complete. Because of having a simpler and minimal GUI it runs better on wine than the other app. There is not glitches, at least I haven't found one. The only functionality not working at all is the "Measure a window" because it only detects I guess the windows programs which are running with wine(caffe7.5 from bottles), in the same bottle. 
But that's not something I really need (I'm more interested in all the other functions[calculating a position xy, or measuring a angle, or the distance between two points, measuring a rectangle or a circle).

I just dislike that there is not option to unselect all the functions (just to activate it whenever I need the function, I sees like it always has something check and working, the least annoying one is the point so that's what I would being using). 

finally, the app would be wonderful if when you click on the color bar next to the RGB textbox,  display an app like KColorChooser to get more information about the color like having other formats of that color, an the possibility to make it darker or lighter or maybe just change the color. [in sumary like having and integrated KColorChooser like how other apps do]
![2022-05-14-182254_2560x1440_scrot](https://user-images.githubusercontent.com/88587370/168452566-26bcaa4c-c7ca-4c6d-a6fa-cfa90277c3c0.png)

**Comment by xandro2021** [comment]
It's awesome that with this app the user can create their own measure unit instead of always using pixels!!!!
It's also nice that the user can choose the format for colors (rgb or html #).
This app is awesome.
But it can be awesomer if it have integrated mini apps like KColorChooser, to play with the selected color by playing with the rgb values or even better the Hue, Sat, Val values to make the color a bit lighter or darker.
It would also be nice to have a mini calculator like Qalculator to make conversions manually, and finally a more friendly ruler that works more like Kruler.
As a tiling window linux user I don't have the problem to open those apps individually. I can make a script to run the three at the same time and run the script with drunner by only writing 3 leters of the script and bum!, or just calling them fast individually by writing the first 3 leters of their name through drunner. But for Windows users that is .... a lot of mambo jambo to open each of them. And the same goes for Linux Users who still used so much the OS GUI to run their programs.
By this app be perfectly running though bottles (flatpak), it means that it is easy to install in any Linux OS now, including Steam Deck and even Chrome OS in which a lot of their users still do things the windows way with GUI. So having that kind of miniapp withing the app could be awesome for them.
![2022-05-15-114126_2560x1440_scrot](https://user-images.githubusercontent.com/88587370/168487347-c4c15f4b-8192-4729-80a0-71637a1b05d1.png)

**Comment by baron1405** [comment]
I have been investigating doing a native port to Linux using Qt and X Window extensions (e.g. XRecord). So far the investigation has uncovered one very troubling find, **Wayland is a show stopper for Meazure**. Starting with Ubuntu 22.04, the Wayland window system is the default rather than X Window. Wayland is by no means a drop-in replacement for X. It is missing functionality that is core to Meazure. For example, Wayland does not allow reading the pointer location outside your own windows, and it does not provide a mechanism for reading arbitrary portions of the screen. There are no reasonable workarounds at this time. It is possible to run Ubuntu 22.04 using X instead of Wayland but that is a user decision. I expect that running the Windows version in emulation will also encounter problems on Wayland due to these critical limitations. Read "[Wayland Breaks Everything!](https://gist.github.com/probonopd/9feb7c20257af5dd915e3a9f2d1f2277)" to get a sense of the scope of breakage caused by Wayland.

**Comment by baron1405** [comment]
I am happy to announce that I have released **[Meazure for Linux](https://github.com/cthing/meazure-linux)**. There are caveats with that release. It **does not support Wayland**, is targeted at Ubuntu (GNOME or KDE) and has only been tested on version 20.04. Nevertheless, it is a complete rewrite of Meazure using the Qt framework and provides a number of significant enhancements over the current Windows version. Enjoy!
