### ISSUE TITLE
Manage Position / Description: use of shortcuts STR+C, STR+X and STR+V?

### ISSUE THREAD

**Issue by ungeahnt** [cthing/meazure#20]
In V2, using one of the keyboard shortcuts STR+C, STR+X or STR+V in 'Positions/Description text window' resulted in a corrupted mpl file. 

These shortcuts seem to be disabled in V3. 

What is the probability that these keyboard shortcuts will be fixed in the foreseeable future?

**Comment by baron1405** [comment]
Thanks for the report! I will investigate the status of the STR/CTRL+C, STR/CTRL+X and STR/CTRL+V keys in the position description text window. I was not aware of the bad behavior of these keys in 2.0 and have not made any explicit changes to their behavior in 3.0 so I suspect this may be due to changes in MFC or Win32 over the years.

**Comment by baron1405** [comment]
The fix is committed. It will be in the 3.0.2 release, which should be out in the next few days.
